name: "Validate syntax"
on:
  push:

jobs:
  validate-dangerfile:
    name: Validate Dangerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Setup
        uses: actions/setup-node@v3

      - name: Validate Dangerfile
        run: npx danger ci -v --text-only --dangerfile dangerfile.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_BASE_URL: "https://api.github.com"
