name: "Validate Dangerfile"
on:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed

jobs:
  validate-dangerfile:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3

      - name: Install packages
        run: yarn

      - name: Validate TypeScript syntax
        run: tsc
